### ISSUE TITLE
Первая ячейка на всех таблицах

### ISSUE THREAD

**Issue by OrWest** [d1stefan0/HomelessApp#3]
Нужно было это сделать как обычное UIView и использовать HeaderView в таблице.

Во-вторых, данные расходиться на разных экранах. Если хочешь их синхронизировать, то сделай класс, где эта инфа храниться будет и всем экранам раздай. Отслеживание изменений можно сделать через нотификации

**Comment by d1stefan0** [comment]
Проблема решена через использование обновления данных в viewDidAppear.
